"""ScholarHarness 的最小领域契约与 Manuscript 边界。"""

from app.scholar.manuscript import ManuscriptSynchronizer, PatchConflict
from app.scholar.approval import (
    ApprovalDecision,
    BuildResult,
    BuildStatus,
    LatexBridgeService,
    LatexDiagnostic,
    PatchApprovalRequest,
    PatchApprovalResult,
    PatchApprovalService,
    PatchApplyResult,
    PatchLifecycleStatus,
    PatchPreview,
    StoredPatch,
)
from app.scholar.models import (
    Contribution,
    ContributionStatus,
    DraftPatch,
    EvidencePack,
    ManuscriptFact,
    ManuscriptSection,
    ManuscriptState,
    ReviewIssue,
    ReviewReport,
)
from app.scholar.project import ScholarProjectStore
from app.scholar.context import ScholarContextBudget
from app.scholar.errors import (
    CapabilityViolation,
    CorrelationConflict,
    ConfigurationError,
    DomainConflict,
    ProviderUnavailable,
    ResumeUnavailable,
    ScholarRuntimeError,
)
from app.scholar.evaluation import (
    HarnessEvaluationCase,
    HarnessEvaluationRecord,
    HarnessEvaluationReport,
    HarnessEvaluationSuite,
    ScholarHarnessEvaluationSuite,
    default_harness_cases,
)
from app.scholar.console import RunEvent, ScholarConsoleProjection
from app.scholar.citation import (
    BibEntryCandidate,
    BibEntrySnapshot,
    BibKeyGenerator,
    BibliographyChange,
    BibliographySynchronizer,
    CitationBinding,
    CitationIdentity,
    CitationRequirement,
    CitationResolutionResult,
    CitationResolutionService,
    CitationStatus,
)
from app.scholar.citation.errors import (
    BibKeyCollision,
    BibMetadataConflict,
    BibPathInvalid,
    BibStaleBaseHash,
    CitationIdentityAmbiguous,
    CitationLifecycleError,
    PartialApplyError,
)
from app.scholar.research import (
    EvidenceCandidate,
    EvidenceRef,
    EvidenceSource,
    DomainSensitivity,
    FreshnessDecision,
    FreshnessMode,
    FreshnessPolicy,
    PaperCandidate,
    PaperSearchResult,
    ResearchBudget,
    ResearchCapabilityService,
    ResearchRequest,
    SectionCandidate,
    SectionSearchResult,
    WebLiteratureAdapter,
)
from app.scholar.research.errors import EvidenceValidationError, InvalidEvidenceLocator, SourceNotFound
from app.scholar.writing import (
    AbstractFactSet,
    CapabilityDenied,
    CapabilityProfile,
    CapabilitySet,
    ClaimSupportResult,
    ClaimSupportService,
    ClaimSupportSubclaim,
    ClaimPlan,
    CitationResolver,
    IntroductionReviewer,
    ChatCompletionSynthesisWriter,
    IntroductionSkill,
    ManuscriptSupervisor,
    MetadataCitationResolver,
    ResearchDelegate,
    ResearchNeed,
    ScholarSkillRuntime,
    SharedManuscriptReviewer,
    SkillDefinition,
    SkillExecutionContext,
    SkillRegistry,
    SkillResult,
    SupportClaimRequest,
    SynthesisWritingService,
    TaskRouter,
    TaskType,
    ScholarWritingService,
    SectionDraft,
    WritingRequest,
    WritingResult,
)

__all__ = [
    "Contribution",
    "ContributionStatus",
    "ApprovalDecision",
    "BuildResult",
    "BuildStatus",
    "DraftPatch",
    "EvidencePack",
    "ManuscriptFact",
    "ManuscriptSection",
    "ManuscriptState",
    "ManuscriptSynchronizer",
    "LatexBridgeService",
    "LatexDiagnostic",
    "PatchConflict",
    "PatchApprovalRequest",
    "PatchApprovalResult",
    "PatchApprovalService",
    "PatchApplyResult",
    "PatchLifecycleStatus",
    "PatchPreview",
    "ReviewIssue",
    "ReviewReport",
    "ScholarProjectStore",
    "ScholarContextBudget",
    "ScholarRuntimeError",
    "ConfigurationError",
    "ProviderUnavailable",
    "ResumeUnavailable",
    "CapabilityViolation",
    "CorrelationConflict",
    "DomainConflict",
    "HarnessEvaluationCase",
    "HarnessEvaluationRecord",
    "HarnessEvaluationReport",
    "HarnessEvaluationSuite",
    "ScholarHarnessEvaluationSuite",
    "default_harness_cases",
    "RunEvent",
    "ScholarConsoleProjection",
    "EvidenceCandidate",
    "EvidenceRef",
    "EvidenceSource",
    "DomainSensitivity",
    "FreshnessDecision",
    "FreshnessMode",
    "FreshnessPolicy",
    "PaperCandidate",
    "PaperSearchResult",
    "ResearchBudget",
    "ResearchCapabilityService",
    "ResearchRequest",
    "SectionCandidate",
    "SectionSearchResult",
    "WebLiteratureAdapter",
    "EvidenceValidationError",
    "InvalidEvidenceLocator",
    "SourceNotFound",
    "StoredPatch",
    "CapabilitySet",
    "CapabilityProfile",
    "CapabilityDenied",
    "AbstractFactSet",
    "ClaimSupportResult",
    "ClaimSupportService",
    "ClaimSupportSubclaim",
    "ClaimPlan",
    "CitationResolver",
    "IntroductionReviewer",
    "ChatCompletionSynthesisWriter",
    "IntroductionSkill",
    "ManuscriptSupervisor",
    "MetadataCitationResolver",
    "ResearchDelegate",
    "ResearchNeed",
    "ScholarSkillRuntime",
    "SharedManuscriptReviewer",
    "SkillDefinition",
    "SkillExecutionContext",
    "SkillRegistry",
    "SkillResult",
    "SupportClaimRequest",
    "SynthesisWritingService",
    "TaskRouter",
    "TaskType",
    "ScholarWritingService",
    "SectionDraft",
    "WritingRequest",
    "WritingResult",
    "BibEntryCandidate",
    "BibEntrySnapshot",
    "BibKeyGenerator",
    "BibliographyChange",
    "BibliographySynchronizer",
    "CitationBinding",
    "CitationIdentity",
    "CitationRequirement",
    "CitationResolutionResult",
    "CitationResolutionService",
    "CitationStatus",
    "BibKeyCollision",
    "BibMetadataConflict",
    "BibPathInvalid",
    "BibStaleBaseHash",
    "CitationIdentityAmbiguous",
    "CitationLifecycleError",
    "PartialApplyError",
]


def __getattr__(name: str) -> object:
    """Lazily expose the Deep Agents adapter without import cycles."""

    if name in {
        "DeepAgentsSkillAdapter",
        "ScholarHarnessResult",
        "ScholarHarnessService",
        "ScholarRuntimeBundle",
        "ScholarRuntimeFactory",
    }:
        from app.scholar.harness import DeepAgentsSkillAdapter, ScholarHarnessResult, ScholarHarnessService
        from app.scholar.composition import ScholarRuntimeBundle, ScholarRuntimeFactory

        return {
            "DeepAgentsSkillAdapter": DeepAgentsSkillAdapter,
            "ScholarHarnessResult": ScholarHarnessResult,
            "ScholarHarnessService": ScholarHarnessService,
            "ScholarRuntimeBundle": ScholarRuntimeBundle,
            "ScholarRuntimeFactory": ScholarRuntimeFactory,
        }[name]
    raise AttributeError(name)


__all__.extend(
    (
        "DeepAgentsSkillAdapter",
        "ScholarHarnessResult",
        "ScholarHarnessService",
        "ScholarRuntimeBundle",
        "ScholarRuntimeFactory",
    )
)
