"""Scholar 领域契约、Manuscript 边界与 CrewAI Runtime 入口。"""

from app.scholar.manuscript import ManuscriptSynchronizer, PatchConflict
from app.scholar.approval import (
    ApprovalDecision,
    BuildResult,
    BuildStatus,
    LatexBridgeService,
    LatexDiagnostic,
    PatchApprovalRequest,
    PatchApprovalResult,
    PatchApprovalService,
    PatchApplyResult,
    PatchLifecycleStatus,
    PatchPreview,
    StoredPatch,
)
from app.scholar.models import (
    Contribution,
    ContributionStatus,
    DraftPatch,
    EvidencePack,
    ManuscriptFact,
    ManuscriptSection,
    ManuscriptState,
    ReviewIssue,
    ReviewReport,
)
from app.scholar.project import (
    ProjectRevisionConflict,
    ProjectWriteBusyError,
    ScholarProjectStore,
)
from app.scholar.errors import (
    CapabilityViolation,
    CorrelationConflict,
    ConfigurationError,
    DomainConflict,
    ProviderUnavailable,
    ResumeUnavailable,
    ScholarRuntimeError,
)
from app.scholar.evaluation import (
    ScholarEvaluationCase,
    ScholarEvaluationRecord,
    ScholarEvaluationReport,
    ScholarEvaluationSuite,
    default_scholar_cases,
)
from app.scholar.console import RunEvent, ScholarConsoleProjection
from app.scholar.citation import (
    BibEntryCandidate,
    BibEntrySnapshot,
    BibKeyGenerator,
    BibliographyChange,
    BibliographySynchronizer,
    CitationBinding,
    CitationIdentity,
    CitationRequirement,
    CitationResolutionResult,
    CitationResolutionService,
    CitationStatus,
)
from app.scholar.citation.errors import (
    BibKeyCollision,
    BibMetadataConflict,
    BibPathInvalid,
    BibStaleBaseHash,
    CitationIdentityAmbiguous,
    CitationLifecycleError,
    PartialApplyError,
)
from app.scholar.research import (
    EvidenceCandidate,
    EvidenceRef,
    EvidenceSource,
    DomainSensitivity,
    FreshnessDecision,
    FreshnessMode,
    FreshnessPolicy,
    PaperCandidate,
    PaperSearchResult,
    ResearchBudget,
    ResearchCapabilityService,
    ResearchRequest,
    SectionCandidate,
    SectionSearchResult,
    WebLiteratureAdapter,
)
from app.scholar.research.errors import EvidenceValidationError, InvalidEvidenceLocator, SourceNotFound
from app.scholar.writing import (
    AbstractFactSet,
    CapabilityDenied,
    CapabilityProfile,
    CapabilitySet,
    ClaimSupportResult,
    ClaimSupportService,
    ClaimSupportSubclaim,
    ClaimPlan,
    CitationResolver,
    IntroductionReviewer,
    ChatCompletionSynthesisWriter,
    IntroductionSkill,
    MetadataCitationResolver,
    ResearchDelegate,
    ResearchNeed,
    ScholarSkillRuntime,
    SharedManuscriptReviewer,
    SkillDefinition,
    SkillExecutionContext,
    SkillRegistry,
    SkillResult,
    SupportClaimRequest,
    SynthesisWritingService,
    TaskRouter,
    TaskType,
    ScholarWritingService,
    SectionDraft,
    WritingRequest,
    WritingResult,
)

__all__ = [
    "Contribution",
    "ContributionStatus",
    "ApprovalDecision",
    "BuildResult",
    "BuildStatus",
    "DraftPatch",
    "EvidencePack",
    "ManuscriptFact",
    "ManuscriptSection",
    "ManuscriptState",
    "ManuscriptSynchronizer",
    "LatexBridgeService",
    "LatexDiagnostic",
    "PatchConflict",
    "PatchApprovalRequest",
    "PatchApprovalResult",
    "PatchApprovalService",
    "PatchApplyResult",
    "PatchLifecycleStatus",
    "PatchPreview",
    "ReviewIssue",
    "ReviewReport",
    "ScholarProjectStore",
    "ProjectRevisionConflict",
    "ProjectWriteBusyError",
    "ScholarRuntimeError",
    "ConfigurationError",
    "ProviderUnavailable",
    "ResumeUnavailable",
    "CapabilityViolation",
    "CorrelationConflict",
    "DomainConflict",
    "ScholarEvaluationCase",
    "ScholarEvaluationRecord",
    "ScholarEvaluationReport",
    "ScholarEvaluationSuite",
    "default_scholar_cases",
    "RunEvent",
    "ScholarConsoleProjection",
    "EvidenceCandidate",
    "EvidenceRef",
    "EvidenceSource",
    "DomainSensitivity",
    "FreshnessDecision",
    "FreshnessMode",
    "FreshnessPolicy",
    "PaperCandidate",
    "PaperSearchResult",
    "ResearchBudget",
    "ResearchCapabilityService",
    "ResearchRequest",
    "SectionCandidate",
    "SectionSearchResult",
    "WebLiteratureAdapter",
    "EvidenceValidationError",
    "InvalidEvidenceLocator",
    "SourceNotFound",
    "StoredPatch",
    "CapabilitySet",
    "CapabilityProfile",
    "CapabilityDenied",
    "AbstractFactSet",
    "ClaimSupportResult",
    "ClaimSupportService",
    "ClaimSupportSubclaim",
    "ClaimPlan",
    "CitationResolver",
    "IntroductionReviewer",
    "ChatCompletionSynthesisWriter",
    "IntroductionSkill",
    "MetadataCitationResolver",
    "ResearchDelegate",
    "ResearchNeed",
    "ScholarSkillRuntime",
    "SharedManuscriptReviewer",
    "SkillDefinition",
    "SkillExecutionContext",
    "SkillRegistry",
    "SkillResult",
    "SupportClaimRequest",
    "SynthesisWritingService",
    "TaskRouter",
    "TaskType",
    "ScholarWritingService",
    "SectionDraft",
    "WritingRequest",
    "WritingResult",
    "BibEntryCandidate",
    "BibEntrySnapshot",
    "BibKeyGenerator",
    "BibliographyChange",
    "BibliographySynchronizer",
    "CitationBinding",
    "CitationIdentity",
    "CitationRequirement",
    "CitationResolutionResult",
    "CitationResolutionService",
    "CitationStatus",
    "BibKeyCollision",
    "BibMetadataConflict",
    "BibPathInvalid",
    "BibStaleBaseHash",
    "CitationIdentityAmbiguous",
    "CitationLifecycleError",
    "PartialApplyError",
]


def __getattr__(name: str) -> object:
    """Lazily expose runtime services without import cycles."""

    if name in {
        "ScholarOrchestrationService",
        "ScholarRunManager",
        "ScholarRunWorker",
        "RunEventStore",
    }:
        from app.orchestration.service import ScholarOrchestrationService
        from app.scholar.runs import ScholarRunManager, ScholarRunWorker
        from app.scholar.events import RunEventStore

        return {
            "ScholarOrchestrationService": ScholarOrchestrationService,
            "ScholarRunManager": ScholarRunManager,
            "ScholarRunWorker": ScholarRunWorker,
            "RunEventStore": RunEventStore,
        }[name]
    raise AttributeError(name)


__all__.extend(
    (
        "ScholarOrchestrationService",
        "ScholarRunManager",
        "ScholarRunWorker",
        "RunEventStore",
    )
)
