"""Cross-domain contracts shared by corpus, evidence and Scholar services."""

from app.contracts.adapters import EvidenceMapper
from app.contracts.domain import (
    CandidateEvidence,
    ExternalEvidenceResolution,
    ContextPack,
    Document,
    EvidenceDirectness,
    EvidenceGrade,
    EvidenceRequest,
    EvidenceSourceType,
    EvidenceState,
    ExternalLocatorType,
    IndexGeneration,
    IndexProfile,
    ResearchDirection,
    ResearchScope,
    ResearchWorkspace,
    SelectedEvidence,
    VerifiedEvidence,
    VerifiedEvidenceBundle,
    Work,
    WorkspaceDocument,
)
from app.contracts.protocols import (
    ContextBuilder,
    EvidenceIntelligenceService,
    KnowledgeEngine,
    ToolGateway,
)

__all__ = [
    "CandidateEvidence",
    "ExternalEvidenceResolution",
    "ContextBuilder",
    "ContextPack",
    "Document",
    "EvidenceDirectness",
    "EvidenceGrade",
    "EvidenceIntelligenceService",
    "EvidenceRequest",
    "EvidenceSourceType",
    "EvidenceState",
    "ExternalLocatorType",
    "IndexGeneration",
    "IndexProfile",
    "KnowledgeEngine",
    "EvidenceMapper",
    "ResearchDirection",
    "ResearchScope",
    "ResearchWorkspace",
    "SelectedEvidence",
    "ToolGateway",
    "VerifiedEvidence",
    "VerifiedEvidenceBundle",
    "Work",
    "WorkspaceDocument",
]
