"""Scholar 的本地 Research Capability Layer。"""

from app.scholar.research.errors import (
    EvidenceValidationError,
    InvalidEvidenceLocator,
    ResearchBudgetExceeded,
    ResearchCapabilityError,
    ResearchRequestError,
    SourceNotFound,
    FreshnessUnavailable,
    WebIdentityConflict,
    WebLiteratureError,
    WebMetadataIncomplete,
    WebProviderRateLimited,
    WebProviderTimeout,
    WebProviderUnavailable,
)
from app.scholar.research.freshness import DomainSensitivity, FreshnessDecision, FreshnessMode, FreshnessPolicy
from app.scholar.research.models import (
    EvidenceCandidate,
    EvidenceRef,
    EvidenceSource,
    PaperCandidate,
    PaperSearchResult,
    ResearchBudget,
    ResearchRequest,
    LiteratureCandidate,
    LiteratureSearchRequest,
    LiteratureSearchResult,
    SectionCandidate,
    SectionSearchResult,
    VerifiedEvidenceResult,
)
from app.scholar.research.service import ResearchCapabilityService, ResearchProgressCallback
from app.scholar.research.web import WebLiteratureAdapter, canonical_identity
from app.scholar.research.budget import (
    BudgetExceeded,
    CapabilityBudget,
    CapabilityBudgetPolicy,
    CapabilityState,
    RecoveryLevel,
)
from app.scholar.research.gateway import ToolGateway, ToolSpec, build_default_gateway
from app.scholar.research.providers import (
    AcademicBackend,
    AcademicLiteratureProviderAdapter,
    BootstrapProviderComposition,
    CandidateKnowledgeRepository,
    CanonicalDocumentParseProviderAdapter,
    build_bootstrap_provider_composition,
)

__all__ = [
    "EvidenceCandidate",
    "EvidenceRef",
    "EvidenceSource",
    "EvidenceValidationError",
    "InvalidEvidenceLocator",
    "PaperCandidate",
    "PaperSearchResult",
    "ResearchBudget",
    "ResearchCapabilityError",
    "ResearchCapabilityService",
    "ResearchProgressCallback",
    "ResearchRequest",
    "ResearchRequestError",
    "SectionCandidate",
    "SectionSearchResult",
    "SourceNotFound",
    "VerifiedEvidenceResult",
    "ResearchBudgetExceeded",
    "FreshnessDecision",
    "FreshnessPolicy",
    "FreshnessMode",
    "DomainSensitivity",
    "WebLiteratureAdapter",
    "canonical_identity",
    "WebLiteratureError",
    "WebProviderTimeout",
    "WebProviderRateLimited",
    "WebProviderUnavailable",
    "WebMetadataIncomplete",
    "WebIdentityConflict",
    "FreshnessUnavailable",
    "LiteratureCandidate",
    "LiteratureSearchRequest",
    "LiteratureSearchResult",
    "AcademicBackend",
    "AcademicLiteratureProviderAdapter",
    "BootstrapProviderComposition",
    "CandidateKnowledgeRepository",
    "CanonicalDocumentParseProviderAdapter",
    "build_bootstrap_provider_composition",
    "BudgetExceeded",
    "CapabilityBudget",
    "CapabilityBudgetPolicy",
    "CapabilityState",
    "RecoveryLevel",
    "ToolGateway",
    "ToolSpec",
    "build_default_gateway",
]
